In [285]:
import pandas as pd

df = pd.read_csv('../3_data/standardized.csv')
df.head(5)

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
0,Senior Security Researcher,CommIT,commit,Senior,Full Time,NaN,"Security-Researcher, Cybersecurity-Researcher,...",Ukraine,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
1,"Director, Revenue Cycle Management",SimpliFed,simplifed,Director,Full Time,NaN,"Revenue-Cycle-Management, Healthcare-Billing, ...",United States,Any,140000.0,...,140000.0,140000.0,140000.0,en,1,0,0,0,0,0
2,SAP IM-MM Consultant 2724,Xideral,xideral,Senior,Full Time,NaN,"SAP-IM-MM-Consultant, Sap-Functional-Consultan...",Mexico,Any,NaN,...,NaN,NaN,NaN,es,0,0,0,0,0,1
3,Creator Talent Manager,Grail Talent,grail-talent,Manager,Full Time,Human Resources,"Talent-Management, Influencer-Marketing, Creat...",Canada,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,1,0,0
4,Senior Program Officer,Pride Foundation,pride-foundation,Senior,Full Time,Product,"Grantmaking, Nonprofit-and-Philanthropy, Commu...",French Polynesia,Any,89000.0,...,89000.0,94000.0,91500.0,en,0,0,0,0,0,1

In [286]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 44131 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  44131 non-null  str
 1   Company Name           44131 non-null  str
 2   Company Slug           44131 non-null  str
 3   seniority              44131 non-null  str
 4   Employment Type        44131 non-null  str
 5   Parent Categories      25613 non-null  str
 6   Category               44119 non-null  str
 7   Location Restrictions  44131 non-null  str
 8   Timezone Restrictions  44131 non-null  str
 9   Min Salary             16335 non-null  float64
 10  Max Salary             16335 non-null  float64
 11  Salary Period          44131 non-null  str
 12  Currency               23965 non-null  str
 13  Published Date         44131 non-null  int64
 14  Published Date(STD)    44131 non-null  str
 15  Expiry Date            44131 non-null  int64
 16  Expiry Date(STD)       44131 non-null  str
 17  Application Link       44131 non-null  str
 18  Excerpt                44131 non-null  str
 19  GUID                   44131 non-null  str
 20  Standard Category      44131 non-null  str
 21  Secondary Category     24749 non-null  str
 22  Region                 44131 non-null  str
 23  Min_Salary_USD_Annual  16335 non-null  float64
 24  Max_Salary_USD_Annual  16335 non-null  float64
 25  Avg_Salary_USD_Annual  16335 non-null  float64
 26  Language               44131 non-null  str
 27  Director               44131 non-null  int64
 28  Entry-level            44131 non-null  int64
 29  Executive              44131 non-null  int64
 30  Manager                44131 non-null  int64
 31  Mid-level              44131 non-null  int64
 32  Senior                 44131 non-null  int64
dtypes: float64(5), int64(8), str(20)
memory usage: 43.1 MB

In [287]:
#1_checking for siniority usability:
df['seniority'].unique()

<ArrowStringArray>
[                                                      'Senior',
                                                     'Director',
                                                      'Manager',
                                                    'Mid-level',
                                                  'Entry-level',
                                              'Manager, Senior',
                                       'Entry-level, Mid-level',
                                          'Director, Executive',
                                            'Mid-level, Senior',
                                                    'Executive',
                                           'Executive, Manager',
                               'Entry-level, Mid-level, Senior',
                                           'Mid-level, Manager',
                                             'Senior, Director',
                                            'Senior, Executive',
                                            'Senior, Mid-level',
                                            'Manager, Director',
                                         'Executive, Mid-level',
                                         'Entry-level, Manager',
                                          'Director, Mid-level',
                                 'Manager, Director, Executive',
                                            'Director, Manager',
                                          'Executive, Director',
              'Senior, Mid-level, Manager, Director, Executive',
                                       'Mid-level, Entry-level',
                                         'Mid-level, Executive',
 'Entry-level, Mid-level, Manager, Senior, Director, Executive',
                               'Mid-level, Entry-level, Senior',
                                            'Executive, Senior']
Length: 29, dtype: str

In [288]:
#we will replace all the words with the same meaning and then we will use the get_dummies method to create a new column for each word

#df['seniority'] = df['seniority'].str.replace('Senior, Manager' ,'Manager, Senior' )
#df['seniority'] = df['seniority'].str.replace('Manager, Executive' ,'Executive, Manager' )
#df['seniority'] = df['seniority'].str.replace('Director, Senior' ,'Senior, Director' )
#df_seniority = df['seniority'].str.get_dummies(', ')
#df = pd.concat([df, df_seniority], axis=1)
#df_seniority

#this part has been moved to standardize_cat.py

In [289]:
#checking for added columns:
df.head(2)

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
0,Senior Security Researcher,CommIT,commit,Senior,Full Time,NaN,"Security-Researcher, Cybersecurity-Researcher,...",Ukraine,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
1,"Director, Revenue Cycle Management",SimpliFed,simplifed,Director,Full Time,NaN,"Revenue-Cycle-Management, Healthcare-Billing, ...",United States,Any,140000.0,...,140000.0,140000.0,140000.0,en,1,0,0,0,0,0

In [290]:
df.info()

<class 'pandas.DataFrame'>
Index: 44131 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  44131 non-null  str
 1   Company Name           44131 non-null  str
 2   Company Slug           44131 non-null  str
 3   seniority              44131 non-null  str
 4   Employment Type        44131 non-null  str
 5   Parent Categories      25613 non-null  str
 6   Category               44119 non-null  str
 7   Location Restrictions  44131 non-null  str
 8   Timezone Restrictions  44131 non-null  str
 9   Min Salary             16335 non-null  float64
 10  Max Salary             16335 non-null  float64
 11  Salary Period          44131 non-null  str
 12  Currency               23965 non-null  str
 13  Published Date         44131 non-null  int64
 14  Published Date(STD)    44131 non-null  str
 15  Expiry Date            44131 non-null  int64
 16  Expiry Date(STD)       44131 non-null  str
 17  Application Link       44131 non-null  str
 18  Excerpt                44131 non-null  str
 19  GUID                   44131 non-null  str
 20  Standard Category      44131 non-null  str
 21  Secondary Category     24749 non-null  str
 22  Region                 44131 non-null  str
 23  Min_Salary_USD_Annual  16335 non-null  float64
 24  Max_Salary_USD_Annual  16335 non-null  float64
 25  Avg_Salary_USD_Annual  16335 non-null  float64
 26  Language               44131 non-null  str
 27  Director               44131 non-null  int64
 28  Entry-level            44131 non-null  int64
 29  Executive              44131 non-null  int64
 30  Manager                44131 non-null  int64
 31  Mid-level              44131 non-null  int64
 32  Senior                 44131 non-null  int64
dtypes: float64(5), int64(8), str(20)
memory usage: 43.1 MB

In [291]:
#2_Validation / Quality Checks for Company Slug:
df['Company Slug'].unique()
print(df["Company Slug"].nunique())
print(df["Company Slug"].isna().sum())
print(df["Company Slug"].duplicated().sum())

9660
0
34471

In [292]:
company_counts = (
    df["Company Slug"]
    .value_counts()
)

print(company_counts.head(20))

print("*"*50)

company_check = (
    df.groupby("Company Slug")["Company Name"]
      .nunique()
      .sort_values(ascending=False)
)

print(company_check.head(20))

Company Slug
mercor                                 1053
bjak                                    809
lifelancer                              733
optimindhealth                          507
pavago                                  330
micro1                                  315
bright-vision-technologies              299
bluelight-consulting                    237
radpartners-avature                     216
huzzle                                  172
tripleten                               167
triptastic-adventures                   152
thehivecareers                          148
scalejet                                133
samsara                                 122
mci-career-services                     118
decisionpoint-corporation               111
clera                                   102
capslock                                 98
syneos-health-india-private-limited      97
Name: count, dtype: int64
**************************************************
Company Slug
aimpoint-digital             2
1komma5                      2
browserstack                 2
apollo                       2
inizio-partners-corp         2
jobrack                      2
bjak                         2
concentrix                   2
interplay-learning           2
airbnb                       2
gopuff                       2
cresol                       2
eaton                        2
crewbloom                    2
applaudo-studios             2
black-tree-gaming-limited    2
zoomph                       2
getmagic                     2
zscaler                      2
essen-medical-associates     2
Name: Company Name, dtype: int64

In [293]:
#3_Validation / Quality Checks for Employment Type
df['Employment Type'].unique()

<ArrowStringArray>
[ 'Full Time',  'Part Time',     'Intern', 'Contractor',      'Other',
  'Volunteer',  'Temporary']
Length: 7, dtype: str

In [294]:
#4_Validation / Quality Checks for Parent Categories
df['Parent Categories'].unique()
#Duo to the Category mapping, we dont make any changes in this column and Catefory column

<ArrowStringArray>
[                                           nan,
                              'Human Resources',
                                      'Product',
                                    'Developer',
              'Management, Product, Operations',
                             'Customer Service',
                      'Customer Service, Sales',
                                'Social Impact',
            'Customer Service, Human Resources',
                             'Sales, Developer',
 ...
             'Marketing, Data Science, Product',
                  'Customer Service, Education',
              'Human Resources, Finance, Sales',
           'Customer Service, Sales, Developer',
                             'Legal, Education',
              'Sales, Data Science, Operations',
 'Operations, Customer Service, Product, Sales',
                  'Content Creator, Operations',
                       'Content Creator, Sales',
                   'Developer, Human Resources']
Length: 353, dtype: str

In [295]:
#5_Validation / Quality Checks for Location Restrictions
df[['Location Restrictions' , 'Region']]
#Duo to the Region mapping, we dont make any changes in this column
#the Region column done in standardization.py and shown here.

      Location Restrictions         Region
0                   Ukraine  Other Regions
1             United States  North America
2                    Mexico          LATAM
3                    Canada  North America
4          French Polynesia  Other Regions
...                     ...            ...
49995         United States  North America
49996         United States  North America
49997         United States  North America
49998                Canada  North America
49999         United States  North America

[44131 rows x 2 columns]

In [296]:
#6_Validation / Quality Checks for Timezone Restrictions
df['Timezone Restrictions'].notna().sum()
#all the values are "any" so this column can be dropped but we will keep it for now
# coz we will get more data in the future and double check this section

np.int64(44131)

In [297]:
#7_Validation / Quality Checks for Min Salary
df[df['Max Salary'].isna() & df['Min Salary'].notna()]
#No sigle input found

Empty DataFrame
Columns: [Title, Company Name, Company Slug, seniority, Employment Type, Parent Categories, Category, Location Restrictions, Timezone Restrictions, Min Salary, Max Salary, Salary Period, Currency, Published Date, Published Date(STD), Expiry Date, Expiry Date(STD), Application Link, Excerpt, GUID, Standard Category, Secondary Category, Region, Min_Salary_USD_Annual, Max_Salary_USD_Annual, Avg_Salary_USD_Annual, Language, Director, Entry-level, Executive, Manager, Mid-level, Senior]
Index: []

[0 rows x 33 columns]

In [298]:
#7.1_Normalization for salaries:
#Normalization functions is dded to the standardize.py. 
# any new currency should be added there
df['Salary Period'].unique()

<ArrowStringArray>
['annual', 'hourly', 'monthly', 'weekly', 'fortnightly']
Length: 5, dtype: str

In [299]:
df['Currency'].unique()

<ArrowStringArray>
[  nan, 'USD', 'PLN', 'INR', 'GBP', 'ZAR', 'PHP', 'CAD', 'AUD', 'EUR', 'MXN',
 'SGD', 'BRL', 'HKD', 'CHF', 'SEK', 'CZK', 'DKK', 'JPY', 'HUF', 'NOK', 'NZD',
 'CLP', 'IDR', 'THB', 'TRY', 'ILS']
Length: 27, dtype: str

In [300]:

df[['Min Salary', 'Max Salary' , 'Currency' , 'Salary Period']]

       Min Salary  Max Salary Currency Salary Period
0             NaN         NaN      NaN        annual
1        140000.0    140000.0      USD        annual
2             NaN         NaN      NaN        annual
3             NaN         NaN      NaN        annual
4         89000.0     94000.0      USD        annual
...           ...         ...      ...           ...
49995         NaN         NaN      USD        hourly
49996         NaN         NaN      NaN        annual
49997         NaN         NaN      NaN        annual
49998     55000.0     65000.0      CAD        annual
49999         NaN         NaN      AUD        hourly

[44131 rows x 4 columns]

In [301]:
#Duo to this datas, the salary normalizer generated in standize.py

df[['Min_Salary_USD_Annual','Max_Salary_USD_Annual','Avg_Salary_USD_Annual']]

       Min_Salary_USD_Annual  Max_Salary_USD_Annual  Avg_Salary_USD_Annual
0                        NaN                    NaN                    NaN
1                 140000.000             140000.000              140000.00
2                        NaN                    NaN                    NaN
3                        NaN                    NaN                    NaN
4                  89000.000              94000.000               91500.00
...                      ...                    ...                    ...
49995                    NaN                    NaN                    NaN
49996                    NaN                    NaN                    NaN
49997                    NaN                    NaN                    NaN
49998              39208.015              46336.745               42772.38
49999                    NaN                    NaN                    NaN

[44131 rows x 3 columns]

In [302]:
#8_Validation / Quality Checks for Published Date and Expiry Date
#we should convert them to date format althoghut they have transformed 
# from timestamps to dates once in the jobgetter.py
df['Published Date(STD)'].describe()

count          44131
unique            27
top       2026-08-03
freq            3746
Name: Published Date(STD), dtype: object

In [303]:
df['Published Date(STD)'] = pd.to_datetime(df['Published Date(STD)'])
df['Expiry Date(STD)'] = pd.to_datetime(df['Expiry Date(STD)'])
df['Published Date(STD)'].info()

<class 'pandas.Series'>
Index: 44131 entries, 0 to 49999
Series name: Published Date(STD)
Non-Null Count  Dtype
--------------  -----
44131 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 689.5 KB

In [304]:
df[['Application Link' ,'Excerpt', 'GUID']]

,Application Link,Excerpt,GUID
0,https://himalayas.app/companies/commit/jobs/se...,DescriptionThe company is the pioneer of Activ...,https://himalayas.app/companies/commit/jobs/se...
1,https://himalayas.app/companies/simplifed/jobs...,"Director, Revenue Cycle ManagementLocation: Re...",https://himalayas.app/companies/simplifed/jobs...
2,https://himalayas.app/companies/xideral/jobs/s...,Consultor SAP IM-MM – Remoto en México 2724Est...,https://himalayas.app/companies/xideral/jobs/s...
3,https://himalayas.app/companies/grail-talent/j...,Fully Remote -Work from anywhere 🌍 Flexible ho...,https://himalayas.app/companies/grail-talent/j...
4,https://himalayas.app/companies/pride-foundati...,TO APPLYPride Foundation is a proud equal oppo...,https://himalayas.app/companies/pride-foundati...
...,...,...,...
49995,https://himalayas.app/companies/upgrade-resour...,Job Title: Piping VDC Detailer IIILocation: Re...,https://himalayas.app/companies/upgrade-resour...
49996,https://himalayas.app/companies/cfocus-softwar...,cFocus Software seeks a Lead ISSO to join our ...,https://himalayas.app/companies/cfocus-softwar...
49997,https://himalayas.app/companies/kalam/jobs/rom...,This is a remote position. Vacancy OverviewAt ...,https://himalayas.app/companies/kalam/jobs/rom...
49998,https://himalayas.app/companies/chargelab-inc/...,Role overviewAs a Bilingual Support Specialist...,https://himalayas.app/companies/chargelab-inc/...
49999,https://himalayas.app/companies/scale-x-soluti...,Category: Legal Location: JOB DESCRIPTION: Vir...,https://himalayas.app/companies/scale-x-soluti...

In [305]:
#9_ Checks for repeated GUID

df = df.drop_duplicates(subset=['GUID'])
df['GUID'].duplicated().sum()

np.int64(0)

In [306]:
#10_ Checks for Excerpt
#As we can see some jobs have dieffrent languages.
# So df['Language'] is generated in standardize.py
df[['Excerpt' , 'Language']]

                                                 Excerpt Language
0      DescriptionThe company is the pioneer of Activ...       en
1      Director, Revenue Cycle ManagementLocation: Re...       en
2      Consultor SAP IM-MM – Remoto en México 2724Est...       es
3      Fully Remote -Work from anywhere 🌍 Flexible ho...       en
4      TO APPLYPride Foundation is a proud equal oppo...       en
...                                                  ...      ...
49995  Job Title: Piping VDC Detailer IIILocation: Re...       en
49996  cFocus Software seeks a Lead ISSO to join our ...       en
49997  This is a remote position. Vacancy OverviewAt ...       en
49998  Role overviewAs a Bilingual Support Specialist...       en
49999  Category: Legal Location: JOB DESCRIPTION: Vir...       en

[43828 rows x 2 columns]

In [307]:
#11_Final Quality Checks for Data Cleaning 
# Looking for suspacious data.
df.describe()

,Min Salary,Max Salary,Published Date,Published Date(STD),Expiry Date,Expiry Date(STD),Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Director,Entry-level,Executive,Manager,Mid-level,Senior
count,1.620700e+04,1.620700e+04,4.382800e+04,43828,4.382800e+04,43828,1.620700e+04,1.620700e+04,1.620700e+04,43828.000000,43828.000000,43828.000000,43828.000000,43828.000000,43828.000000
mean,1.244332e+05,1.711422e+05,1.786054e+09,2026-08-06 15:18:20.994797,1.790830e+09,2026-09-30 21:11:34.898238,1.111708e+05,1.537175e+05,1.324442e+05,0.068130,0.113900,0.032011,0.128343,0.347654,0.372753
min,5.000000e-01,7.000000e-01,1.784882e+09,2026-07-24 00:00:00,1.787363e+09,2026-08-22 00:00:00,4.800000e+01,1.000000e+03,9.440100e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.600000e+04,8.500000e+04,1.785444e+09,2026-07-31 00:00:00,1.790477e+09,2026-09-27 00:00:00,6.700000e+04,8.656285e+04,7.750000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000e+05,1.400000e+05,1.786083e+09,2026-08-07 00:00:00,1.791128e+09,2026-10-04 00:00:00,1.000000e+05,1.400000e+05,1.218500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.440000e+05,1.983960e+05,1.786585e+09,2026-08-13 00:00:00,1.791702e+09,2026-10-11 00:00:00,1.400000e+05,1.941000e+05,1.685000e+05,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,4.300000e+07,5.300000e+07,1.787128e+09,2026-08-19 00:00:00,1.794535e+09,2026-11-13 00:00:00,1.040000e+06,1.500000e+06,1.040000e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,4.586680e+05,5.785494e+05,6.138113e+05,NaN,1.178849e+06,NaN,7.020650e+04,1.014935e+05,8.376168e+04,0.251972,0.317693,0.176033,0.334475,0.476231,0.483543

In [308]:
#checking lowst paid jobs:
df.sort_values('Min_Salary_USD_Annual', ascending=True).head()#-----------------------first ones

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
47289,Senior Marketing Analyst LatAm,Plurio,plurio,Senior,Contractor,NaN,"Lead-Marketing-Analyst, Senior-Marketing-Analy...",Worldwide / Unrestricted,Any,4.0,...,48.00,66000.00,33024.00,en,0,0,0,0,0,1
20,Web Engineer Trainee (Internship Track: Full S...,KraftPixel Digital Solutions Private Limited,kraftpixel-digital-solutions-private-limited,Entry-level,Intern,NaN,"Web-engineering, Fullstack-Development, Web-De...",United States,Any,2500.0,...,314.67,1573.35,944.01,en,0,1,0,0,0,0
16627,Underwriter,Hire Hangar,hire-hangar,Mid-level,Contractor,NaN,"Underwriter, Insurance-Underwriter, Contract-U...","Argentina, Bolivia, Chile, Colombia, Cuba, Ecu...",Any,1000.0,...,1000.00,1000.00,1000.00,en,0,0,0,0,1,0
44079,Underwriting Analyst,Hire Hangar,hire-hangar,"Entry-level, Mid-level",Contractor,NaN,"Underwriting-Analyst, Underwriting-Associate, ...","Argentina, Bolivia, Chile, Colombia, Cuba, Ecu...",Any,1000.0,...,1000.00,1000.00,1000.00,en,0,1,0,0,1,0
766,Graduate School Adjunct Instructor- Pool Fall ...,Clarkson University,clarkson-university,Mid-level,Part Time,NaN,"Adjunct-Instructor, Higher-Education, Graduate...",United States,Any,1000.0,...,1000.00,12000.00,6500.00,en,0,0,0,0,1,0

In [309]:
#checking Highest paid jobs:
df.sort_values('Max_Salary_USD_Annual', ascending=False).head()

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
47442,President of Mortgage Wholesale Lending,AmeriSave Mortgage Corp.,amerisave-mortgage-corp,Executive,Full Time,NaN,"Executive-Management, Mortgage-Lending, Wholes...",United States,Any,300000.0,...,300000.0,1500000.0,900000.0,en,0,0,1,0,0,0
46468,Radiologist - 1099,name,prenuvo,Senior,Contractor,NaN,"Radiology, Diagnostic-Imaging, Medical-Imaging...",United States,Any,16000.0,...,192000.0,1152000.0,672000.0,en,0,0,0,0,0,1
38909,"Sr. Data Science Manager, Member & Algo Intell...",Netflix,netflix,"Manager, Senior",Full Time,NaN,"Data-Science-Management, Analytics-Leadership,...",United States,Any,600000.0,...,600000.0,1050000.0,825000.0,en,0,0,0,1,0,1
7125,LLM Agent Engineer - Production,mercor,mercor,Mid-level,Contractor,"Developer, Data Science","LLM-Agent-Engineering, AI-ML-Engineering, Prod...",Germany,Any,100.0,...,208000.0,1040000.0,624000.0,en,0,0,0,0,1,0
3342,LLM Systems Engineer - Fully Remote | Upto $50...,mercor,mercor,Mid-level,Contractor,Data Science,"LLM-Systems-Engineering, AI-Agent-Development,...",United Kingdom,Any,100.0,...,208000.0,1040000.0,624000.0,en,0,0,0,0,1,0

In [310]:
df.sort_values(by='Avg_Salary_USD_Annual' , ascending=False).head(5).T

,1807,47442,38937,38909,39999
Title,CLIA Laboratory Director (m/f/d),President of Mortgage Wholesale Lending,Remote Overnight General Radiologist - Synergy...,"Sr. Data Science Manager, Member & Algo Intell...",Remote Overnight Emergency Radiologist - Jeffe...
Company Name,ProtaGene,AmeriSave Mortgage Corp.,Radiology Partners,Netflix,Radiology Partners
Company Slug,protagene,amerisave-mortgage-corp,radpartners-avature,netflix,radpartners-avature
seniority,"Director, Executive",Executive,Senior,"Manager, Senior",Senior
Employment Type,Contractor,Full Time,Full Time,Full Time,Full Time
Parent Categories,NaN,NaN,NaN,NaN,NaN
Category,"Laboratory-Director, Clinical-Diagnostics, Mol...","Executive-Management, Mortgage-Lending, Wholes...","Radiologist, Diagnostic-Radiology, Remote-Radi...","Data-Science-Management, Analytics-Leadership,...","Emergency-Radiology, Diagnostic-Radiologist, R..."
Location Restrictions,United States,United States,United States,United States,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,500.0,300000.0,750000.0,600000.0,600000.0
Max Salary,500.0,1500000.0,1000000.0,1050000.0,1000000.0
Salary Period,hourly,annual,annual,annual,annual
Currency,USD,USD,USD,USD,USD
Published Date,1787015877,1785144412,1785432854,1785434009,1785399717
Published Date(STD),2026-08-18 00:00:00,2026-07-27 00:00:00,2026-07-30 00:00:00,2026-07-30 00:00:00,2026-07-30 00:00:00
Expiry Date,1792199876,1790328411,1790616854,1790618008,1790583716
Expiry Date(STD),2026-10-17 00:00:00,2026-09-25 00:00:00,2026-09-28 00:00:00,2026-09-28 00:00:00,2026-09-28 00:00:00
Application Link,https://himalayas.app/companies/protagene/jobs...,https://himalayas.app/companies/amerisave-mort...,https://himalayas.app/companies/radpartners-av...,https://himalayas.app/companies/netflix/jobs/s...,https://himalayas.app/companies/radpartners-av...
Excerpt,Your Responsibilities• Act as part-time/consul...,Lead the Future of Mortgage LendingAmeriSave M...,General information Press space or enter keys ...,"At Netflix, our mission is to entertain the wo...",General information Press space or enter keys ...
GUID,https://himalayas.app/companies/protagene/jobs...,https://himalayas.app/companies/amerisave-mort...,https://himalayas.app/companies/radpartners-av...,https://himalayas.app/companies/netflix/jobs/s...,https://himalayas.app/companies/radpartners-av...
Standard Category,Research & Science,Operations & Management,Healthcare,Data & AI,Healthcare
Secondary Category,Healthcare,Sales,NaN,NaN,NaN
Region,North America,North America,North America,North America,North America
Min_Salary_USD_Annual,1040000.0,300000.0,750000.0,600000.0,600000.0
Max_Salary_USD_Annual,1040000.0,1500000.0,1000000.0,1050000.0,1000000.0
Avg_Salary_USD_Annual,1040000.0,900000.0,875000.0,825000.0,800000.0
Language,en,en,en,en,en
Director,1,0,0,0,0
Entry-level,0,0,0,0,0
Executive,1,1,0,0,0
Manager,0,0,0,1,0
Mid-level,0,0,0,0,0
Senior,0,0,1,1,1

In [311]:
#Contractors(Employment Type) and hourly(Salary Period) must not be compared to others in analytics

In [312]:
#removing annual standardization in Contractor employment type:
#df.loc[
#    df['Employment Type'] == 'Contractor',
#['Min_Salary_USD_Annual','Max_Salary_USD_Annual','Avg_Salary_USD_Annual']
#] = None

#df[df['Employment Type'] == 'Contractor'][['Min_Salary_USD_Annual','Max_Salary_USD_Annual','Avg_Salary_USD_Annual']]

In [313]:
df[df["Employment Type"] == 'Contractor']

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
28,CONTRACT POSTION: Technical Editor / Writer,Verra,verra,Mid-level,Contractor,Content Creator,"Technical-Editor, Technical-Writer, Copy-Edito...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,1,0
40,Hospitalist Physician,micro1,micro1,Mid-level,Contractor,NaN,"Physician-Hospitalist, Hospital-Medicine-Physi...",Worldwide / Unrestricted,Any,70.0,...,145600.0,208000.0,176800.0,en,0,0,0,0,1,0
48,1st Line Support Engineer - Remote job (Shifts...,Openprovider,openprovider,Mid-level,Contractor,"Customer Service, Developer","1st-Line-Support, Technical-Support, Customer-...",Colombia,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,1,0
55,Clinical Psychologist,Valera Health,valera-health,Mid-level,Contractor,Healthcare,"Clinical-Psychology, Therapy, Mental-Health-Co...",United States,Any,75.0,...,156000.0,272480.0,214240.0,en,0,0,0,0,1,0
76,School Psychologist,AXIS Teletherapy,axis-teletherapy,Mid-level,Contractor,NaN,"School-Psychology, School-Psychologist, Teleth...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49976,Content Writer,FreeUp,freeup,Senior,Contractor,Content Creator,"Content-Writer, Blog-Writer, SEO-Writer, Digit...",Philippines,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
49981,3D Character Artist,Streamline Studios,streamline-studios,Senior,Contractor,NaN,"3D-Character-Artist, Character-Artist, Game-Ar...",Malaysia,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
49984,Interim CFO – Banking/Credit Union Industry,"Charles River CFO, Inc.",charles-river-cfo-inc,Executive,Contractor,NaN,"Interim-CFO, Fractional-CFO, Banking-CFO, Cred...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,1,0,0,0
49993,Fuzhou - English Remote Interpreter,Kalam,kalam,Senior,Contractor,NaN,"Interpreters, Remote-Interpreter, Medical-Inte...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
49997,Romanian - English Remote Interpreter,Kalam,kalam,Senior,Contractor,NaN,"Interpreting, Language-Services, Translation-a...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1

In [314]:
df[df['Max_Salary_USD_Annual']/df['Min_Salary_USD_Annual'] > 3].head(5) #-------------big ratio for junior

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
13,Korean Language Data Contributor (Multimodal) ...,Invisible Technologies,inv,Entry-level,Full Time,NaN,"Language-and-Linguistics, AI-Training, Data-An...",South Korea,Any,6.0,...,12480.00,135200.00,73840.00,en,0,1,0,0,0,0
20,Web Engineer Trainee (Internship Track: Full S...,KraftPixel Digital Solutions Private Limited,kraftpixel-digital-solutions-private-limited,Entry-level,Intern,NaN,"Web-engineering, Fullstack-Development, Web-De...",United States,Any,2500.0,...,314.67,1573.35,944.01,en,0,1,0,0,0,0
62,Program Manager,Codekeeper,codekeeper,Manager,Full Time,"Product, Operations","Project-Management, Product-Management, Progra...",South Africa,Any,10000.0,...,10000.00,50000.00,30000.00,en,0,0,0,1,0,0
220,Vietnamese Voice Actor - AI Trainer,Invisible Technologies,inv,Mid-level,Full Time,NaN,"Voice-Acting, Linguistics, AI-Training, Data-A...",Vietnam,Any,6.0,...,12480.00,135200.00,73840.00,en,0,0,0,0,1,0
236,Client Success Specialist (LegalTech),Codekeeper,codekeeper,Mid-level,Full Time,Customer Service,"Customer-Success, Legal-Tech, Client-Success-S...",Argentina,Any,10000.0,...,10000.00,100000.00,55000.00,en,0,0,0,0,1,0

In [315]:
#1_2 Nan Salary Values:
#Relation with Standard Category
(df[df['Min_Salary_USD_Annual'].isna()].groupby('Standard Category')['Title'].count()).sort_values(ascending=False)

Standard Category
Sales                      3742
Software Development       3459
Healthcare                 2658
Customer Service           2628
Data & AI                  2152
Engineering                2008
Operations & Management    1992
Marketing                  1634
Finance & Accounting       1422
Human Resources            1267
IT & Cybersecurity         1221
Design & Creative           792
Product                     706
Education                   669
Writing & Content           663
Legal                       428
Research & Science          172
Other                         8
Name: Title, dtype: int64

In [316]:
(df[df['Min_Salary_USD_Annual'].isna()].groupby('Company Slug')['Title'].count()).sort_values(ascending=False)

Company Slug
mercor                     855
bjak                       784
lifelancer                 377
pavago                     313
micro1                     272
                          ...
1nhealth                     1
1840-company                 1
16vc                         1
10x-value-partners-gmbh      1
10x-genomics                 1
Name: Title, Length: 6992, dtype: int64

In [317]:
df[df['Company Slug'] == 'mercor']['Standard Category'].unique()

<ArrowStringArray>
[      'Writing & Content',      'IT & Cybersecurity',
               'Data & AI',      'Research & Science',
         'Human Resources',    'Finance & Accounting',
              'Healthcare',                   'Legal',
        'Customer Service',             'Engineering',
       'Design & Creative', 'Operations & Management',
                   'Sales',               'Education',
               'Marketing',    'Software Development',
                 'Product']
Length: 17, dtype: str

In [335]:
df['Employment Type'].unique()

<ArrowStringArray>
[ 'Full Time',  'Part Time',     'Intern', 'Contractor',      'Other',
  'Volunteer',  'Temporary']
Length: 7, dtype: str

In [336]:
#Luke Barousse:
#df_notna = df.dropna(subset='Min Salary',axis=0) #saved for later  (df.notna())
df_no_contractors = df[df['Employment Type'] != 'Contractor']
df_fulltime = df[df['Employment Type'] == 'Full Time']
salary_stats = (df_fulltime.groupby('Standard Category')['Avg_Salary_USD_Annual'].agg(['min' , 'max' ,'mean', 'median' , 'count']))
salary_stats['mean-median'] = (salary_stats['mean'] - salary_stats['median']).abs()
salary_stats =  salary_stats.sort_values(by='mean-median' , ascending=False)
salary_stats.style.format(lambda x: f'{x/1000:.1f}k',subset=['min' , 'max' ,'mean', 'median', 'mean-median'])

#important jobs are in others.

# A high gap between mean and median in Healthcare shows right-skewness due to high salary outliers.
# Median is safer than mean for salary analysis here because it is not affected by extreme values.
# Small sample size in Finance (only 21 rows) makes its overall statistical trends unreliable.
# Having 86 rows in the 'Other' category highlights the need to improve the category mapping logic.

In [319]:
#checking HealthCare Duo to its mean_median dieffrence:
df[(df['Standard Category'] == 'Healthcare') & (df['Employment Type'] != 'Contractor')].sort_values('Min_Salary_USD_Annual', ascending=False).head(5).T

,38937,32696,39015,42117,37604
Title,Remote Overnight General Radiologist - Synergy...,Remote FULL-TIME Diagnostic Radiologist (42 we...,Remote Day Neuroradiologist - Radiology Partne...,Remote Radiologist Mercy Springfield Missouri,Remote Evening Diagnostic Radiologist - Radiol...
Company Name,Radiology Partners,"IntelliRad Imaging, LLC",Radiology Partners,Mercy,name
Company Slug,radpartners-avature,intellirad-imaging-llc,radpartners-avature,mercy,radpartners-avature
seniority,Senior,Senior,Senior,Senior,Senior
Employment Type,Full Time,Full Time,Full Time,Full Time,Full Time
Parent Categories,NaN,NaN,NaN,NaN,NaN
Category,"Radiologist, Diagnostic-Radiology, Remote-Radi...","Diagnostic-Radiology, General-Radiology, Radio...","Neuroradiology, Diagnostic-Radiology, Medical-...","Radiology, Emergency-Radiology, Teleradiology,...","Diagnostic-Radiology, Radiology, Radiologist, ..."
Location Restrictions,United States,United States,United States,United States,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,750000.0,650000.0,650000.0,625000.0,600000.0
Max Salary,1000000.0,900000.0,650000.0,625000.0,650000.0
Salary Period,annual,annual,annual,annual,annual
Currency,USD,USD,USD,USD,USD
Published Date,1785432854,1785789322,1785430130,1785353971,1785470521
Published Date(STD),2026-07-30 00:00:00,2026-08-04 00:00:00,2026-07-30 00:00:00,2026-07-29 00:00:00,2026-07-31 00:00:00
Expiry Date,1790616854,1788319160,1790614129,1790537970,1790654520
Expiry Date(STD),2026-09-28 00:00:00,2026-09-02 00:00:00,2026-09-28 00:00:00,2026-09-27 00:00:00,2026-09-29 00:00:00
Application Link,https://himalayas.app/companies/radpartners-av...,https://himalayas.app/companies/intellirad-ima...,https://himalayas.app/companies/radpartners-av...,https://himalayas.app/companies/mercy/jobs/rem...,https://himalayas.app/companies/radpartners-av...
Excerpt,General information Press space or enter keys ...,"IntelliRad Imaging, LLC is seeking a Board Cer...",General information Press space or enter keys ...,Find your calling at Mercy! Mercy Hospital Spr...,General information Press space or enter keys ...
GUID,https://himalayas.app/companies/radpartners-av...,https://himalayas.app/companies/intellirad-ima...,https://himalayas.app/companies/radpartners-av...,https://himalayas.app/companies/mercy/jobs/rem...,https://himalayas.app/companies/radpartners-av...
Standard Category,Healthcare,Healthcare,Healthcare,Healthcare,Healthcare
Secondary Category,NaN,NaN,NaN,NaN,NaN
Region,North America,North America,North America,North America,North America
Min_Salary_USD_Annual,750000.0,650000.0,650000.0,625000.0,600000.0
Max_Salary_USD_Annual,1000000.0,900000.0,650000.0,625000.0,650000.0
Avg_Salary_USD_Annual,875000.0,775000.0,650000.0,625000.0,625000.0
Language,en,en,en,en,en
Director,0,0,0,0,0
Entry-level,0,0,0,0,0
Executive,0,0,0,0,0
Manager,0,0,0,0,0
Mid-level,0,0,0,0,0
Senior,1,1,1,1,1

In [320]:
#checking HealthCare Duo to its max:
df[(df['Standard Category'] == 'Customer Service') & (df['Employment Type'] != 'Contractor')].sort_values('Min_Salary_USD_Annual', ascending=False).head(5).T

,25298,35088,30047,43310,9060
Title,"RVP Customer Experience, Americas","Director, Lifecycle & Customer Growth",VP Consulting Sales - Banking Capital Markets ...,"Vice President, Professional Services","Director, Global Developer Success"
Company Name,Claroty,Gametime,EXL,Bonterra,Temporal Technologies
Company Slug,claroty,gametime,exl,bonterra,temporal-technologies
seniority,Executive,Director,Executive,Executive,Director
Employment Type,Full Time,Full Time,Full Time,Full Time,Full Time
Parent Categories,Customer Service,"Marketing, Customer Service",NaN,NaN,NaN
Category,"Customer-Success, Customer-Experience, Sales-L...","CRM-Director, Director-Of-Lifecycle-Marketing,...","Vice-President-of-Consulting-Sales, Banking-Sa...","Vice-President-Professional-Services, Professi...","Director-Of-Technical-Support, Director-of-Dev..."
Location Restrictions,United States,United States,United States,United States,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,250000.0,240000.0,230000.0,228000.0,220000.0
Max Salary,285000.0,270000.0,280000.0,265000.0,270000.0
Salary Period,annual,annual,annual,annual,annual
Currency,USD,USD,USD,USD,USD
Published Date,1786132841,1785753183,1785916786,1785323940,1786753235
Published Date(STD),2026-08-07 00:00:00,2026-08-03 00:00:00,2026-08-05 00:00:00,2026-07-29 00:00:00,2026-08-15 00:00:00
Expiry Date,1791316840,1790937183,1791100785,1790507939,1791937235
Expiry Date(STD),2026-10-06 00:00:00,2026-10-02 00:00:00,2026-10-04 00:00:00,2026-09-27 00:00:00,2026-10-14 00:00:00
Application Link,https://himalayas.app/companies/claroty/jobs/r...,https://himalayas.app/companies/gametime/jobs/...,https://himalayas.app/companies/exl/jobs/vp-co...,https://himalayas.app/companies/bonterra/jobs/...,https://himalayas.app/companies/temporal-techn...
Excerpt,DescriptionWe’re growing and looking to hire a...,About Us:Live experiences help people cross to...,• Base salary range: $230k - $280k • Total com...,"US Salary: $228,000 - $265,000 w/25% annual bo...",About UsTemporal is an open source programming...
GUID,https://himalayas.app/companies/claroty/jobs/r...,https://himalayas.app/companies/gametime/jobs/...,https://himalayas.app/companies/exl/jobs/vp-co...,https://himalayas.app/companies/bonterra/jobs/...,https://himalayas.app/companies/temporal-techn...
Standard Category,Customer Service,Customer Service,Customer Service,Customer Service,Customer Service
Secondary Category,Sales,Marketing,Sales,NaN,Operations & Management
Region,North America,North America,North America,North America,North America
Min_Salary_USD_Annual,250000.0,240000.0,230000.0,228000.0,220000.0
Max_Salary_USD_Annual,285000.0,270000.0,280000.0,265000.0,270000.0
Avg_Salary_USD_Annual,267500.0,255000.0,255000.0,246500.0,245000.0
Language,en,en,en,en,en
Director,0,1,0,0,1
Entry-level,0,0,0,0,0
Executive,1,0,1,1,0
Manager,0,0,0,0,0
Mid-level,0,0,0,0,0
Senior,0,0,0,0,0

In [321]:
df[(df['Standard Category'] == 'Operations & Management') & (df['Employment Type'] != 'Contractor')].sort_values('Min_Salary_USD_Annual', ascending=False).head(5).T

,1621,11008,47442,30950,1074
Title,Head of Operations,"SVP, Agentic Transformation",President of Mortgage Wholesale Lending,Strategic Project Lead,CEO Franchisor
Company Name,Wonderly,Blend360,AmeriSave Mortgage Corp.,micro1,Leap Brands
Company Slug,wonderly,blend360,amerisave-mortgage-corp,micro1,leap-brands
seniority,"Director, Executive",Executive,Executive,"Manager, Director",Executive
Employment Type,Full Time,Full Time,Full Time,Full Time,Full Time
Parent Categories,Operations,NaN,NaN,NaN,Management
Category,"Head-of-Operations, Head-of-Business-Operation...","Management-Consulting, AI-Transformation, Digi...","Executive-Management, Mortgage-Lending, Wholes...","Strategic-Project-Lead, Strategic-Project-Mana...","CEO-Franchisor, Executive-Leadership, Franchis..."
Location Restrictions,United States,United States,United States,Worldwide / Unrestricted,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,400000.0,350000.0,300000.0,300000.0,300000.0
Max Salary,650000.0,500000.0,1500000.0,500000.0,350000.0
Salary Period,annual,annual,annual,annual,annual
Currency,USD,USD,USD,USD,USD
Published Date,1787025234,1786719218,1785144412,1785843561,1787085067
Published Date(STD),2026-08-18 00:00:00,2026-08-14 00:00:00,2026-07-27 00:00:00,2026-08-04 00:00:00,2026-08-19 00:00:00
Expiry Date,1792209233,1791903217,1790328411,1791027561,1789527213
Expiry Date(STD),2026-10-17 00:00:00,2026-10-13 00:00:00,2026-09-25 00:00:00,2026-10-03 00:00:00,2026-09-16 00:00:00
Application Link,https://himalayas.app/companies/wonderly/jobs/...,https://himalayas.app/companies/blend360/jobs/...,https://himalayas.app/companies/amerisave-mort...,https://himalayas.app/companies/micro1/jobs/st...,https://himalayas.app/companies/leap-brands/jo...
Excerpt,About WonderlyWonderly is an end-to-end vertic...,This is a once-in-a-generation leadership role...,Lead the Future of Mortgage LendingAmeriSave M...,Job Title: Strategic Project Lead Job Type: Fu...,Chief Executive Officer (CEO) – Emerging Franc...
GUID,https://himalayas.app/companies/wonderly/jobs/...,https://himalayas.app/companies/blend360/jobs/...,https://himalayas.app/companies/amerisave-mort...,https://himalayas.app/companies/micro1/jobs/st...,https://himalayas.app/companies/leap-brands/jo...
Standard Category,Operations & Management,Operations & Management,Operations & Management,Operations & Management,Operations & Management
Secondary Category,NaN,NaN,Sales,NaN,NaN
Region,North America,North America,North America,Worldwide / Unrestricted,North America
Min_Salary_USD_Annual,400000.0,350000.0,300000.0,300000.0,300000.0
Max_Salary_USD_Annual,650000.0,500000.0,1500000.0,500000.0,350000.0
Avg_Salary_USD_Annual,525000.0,425000.0,900000.0,400000.0,325000.0
Language,en,en,en,en,en
Director,1,0,0,1,0
Entry-level,0,0,0,0,0
Executive,1,1,1,0,1
Manager,0,0,0,1,0
Mid-level,0,0,0,0,0
Senior,0,0,0,0,0

In [337]:
#lets check the min numbers those seem wierd:
salary_stats.style.format(lambda x: f'{x/1000:.1f}k',subset=['min' , 'max' ,'mean', 'median', 'mean-median'])

In [327]:
df[(df['Standard Category'] == 'Software Development')].sort_values('Min_Salary_USD_Annual' ).head(5).T

,20,17643,24293,11756,5509
Title,Web Engineer Trainee (Internship Track: Full S...,Mobile Manual QA Engineer,Staff DevOps Engineer,Vue.js Developer,JO-202567 : Full Stack Web Developer
Company Name,KraftPixel Digital Solutions Private Limited,what3words,what3words,ASPER BROTHERS,KonnectHub
Company Slug,kraftpixel-digital-solutions-private-limited,what3words,what3words,asper-brothers,konnecthub
seniority,Entry-level,Mid-level,Senior,Senior,Mid-level
Employment Type,Intern,Full Time,Full Time,Contractor,Part Time
Parent Categories,NaN,Developer,NaN,NaN,Developer
Category,"Web-engineering, Fullstack-Development, Web-De...","Mobile-QA-Engineer, QA-Manual-Engineer, Mobile...","Staff-DevOps-Engineer, Staff-Software-Engineer...","Frontend-Development, Web-Development, Softwar...","Full-Stack-Developer, Web-Developer, Front-End..."
Location Restrictions,United States,Vietnam,Vietnam,Poland,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,2500.0,1500.0,3500.0,15000.0,25000.0
Max Salary,12500.0,2000.0,4500.0,20000.0,25000.0
Salary Period,monthly,annual,annual,annual,monthly
Currency,INR,USD,USD,PLN,PHP
Published Date,1787125650,1786416359,1786161574,1786704454,1786882875
Published Date(STD),2026-08-19 00:00:00,2026-08-11 00:00:00,2026-08-08 00:00:00,2026-08-14 00:00:00,2026-08-16 00:00:00
Expiry Date,1792309650,1791600358,1791345574,1791888454,1792066875
Expiry Date(STD),2026-10-18 00:00:00,2026-10-10 00:00:00,2026-10-07 00:00:00,2026-10-13 00:00:00,2026-10-15 00:00:00
Application Link,https://himalayas.app/companies/kraftpixel-dig...,https://himalayas.app/companies/what3words/job...,https://himalayas.app/companies/what3words/job...,https://himalayas.app/companies/asper-brothers...,https://himalayas.app/companies/konnecthub/job...
Excerpt,Category: IT Services Location: KraftPixel is ...,Our mission is to become the global standard f...,Our mission is to become the global standard f...,An experienced middle and senior Vue. js Devel...,This is a remote position. Full Stack Web Deve...
GUID,https://himalayas.app/companies/kraftpixel-dig...,https://himalayas.app/companies/what3words/job...,https://himalayas.app/companies/what3words/job...,https://himalayas.app/companies/asper-brothers...,https://himalayas.app/companies/konnecthub/job...
Standard Category,Software Development,Software Development,Software Development,Software Development,Software Development
Secondary Category,Engineering,Engineering,Engineering,NaN,NaN
Region,North America,Other Regions,Other Regions,Europe / EU,North America
Min_Salary_USD_Annual,314.67,1500.0,3500.0,4025.43,4923.9
Max_Salary_USD_Annual,1573.35,2000.0,4500.0,5367.24,4923.9
Avg_Salary_USD_Annual,944.01,1750.0,4000.0,4696.335,4923.9
Language,en,en,en,en,en
Director,0,0,0,0,0
Entry-level,1,0,0,0,0
Executive,0,0,0,0,0
Manager,0,0,0,0,0
Mid-level,0,1,0,0,1
Senior,0,0,1,1,0

In [324]:
df['Salary Period'].unique()

<ArrowStringArray>
['annual', 'hourly', 'monthly', 'weekly', 'fortnightly']
Length: 5, dtype: str

In [332]:
df_no_contractors[(df_no_contractors['Standard Category'] == 'Research & Science')].sort_values('Min_Salary_USD_Annual' ).head(5).T

,29366,20846,15658,26424,27682
Title,"UX Researcher | Tokyo, Japan","Sr. Associate, CX Market Research",Explorer | Research Manager | Shopper Research...,Biostatistical Scientist,Grants Research Analyst
Company Name,AnswerLab,J.D. Power,Savanta,Macks Lifesciences,TFG
Company Slug,answerlab,j-d-power,savanta,macks-lifesciences,tfg
seniority,Mid-level,Senior,Manager,Mid-level,Entry-level
Employment Type,Full Time,Full Time,Full Time,Full Time,Full Time
Parent Categories,Design,Marketing,Marketing,NaN,Marketing
Category,"Research, UX-Research, Qualitative-Research, R...","CX-Market-Research, Customer-Experience, Marke...","Research-Manager, Shopper-Research, Market-Res...","Biostatistics-Jobs, Senior-Biostatistician, Ph...","Grants-Research, Grant-writing, Research-Analy..."
Location Restrictions,Japan,Canada,Canada,Worldwide / Unrestricted,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,6000000.0,60000.0,70000.0,50000.0,55000.0
Max Salary,10000000.0,70000.0,80000.0,75000.0,75000.0
Salary Period,annual,annual,annual,annual,annual
Currency,JPY,CAD,CAD,USD,USD
Published Date,1785986595,1786257636,1786531351,1786101120,1786052274
Published Date(STD),2026-08-06 00:00:00,2026-08-09 00:00:00,2026-08-12 00:00:00,2026-08-07 00:00:00,2026-08-07 00:00:00
Expiry Date,1791170595,1791441635,1791715350,1788600550,1791236273
Expiry Date(STD),2026-10-05 00:00:00,2026-10-08 00:00:00,2026-10-11 00:00:00,2026-09-05 00:00:00,2026-10-06 00:00:00
Application Link,https://himalayas.app/companies/answerlab/jobs...,https://himalayas.app/companies/j-d-power/jobs...,https://himalayas.app/companies/savanta/jobs/e...,https://himalayas.app/companies/macks-lifescie...,https://himalayas.app/companies/tfg/jobs/grant...
Excerpt,About AnswerLabAnswerLab helps pioneering lead...,"Job Description: Title: Sr. Associate, CX Mar...",Explorer is seeking a Research Manager to join...,Macks Life Science is a computational life-sci...,Position Overview The Grants Research Analyst ...
GUID,https://himalayas.app/companies/answerlab/jobs...,https://himalayas.app/companies/j-d-power/jobs...,https://himalayas.app/companies/savanta/jobs/e...,https://himalayas.app/companies/macks-lifescie...,https://himalayas.app/companies/tfg/jobs/grant...
Standard Category,Research & Science,Research & Science,Research & Science,Research & Science,Research & Science
Secondary Category,NaN,NaN,NaN,NaN,NaN
Region,APAC,North America,North America,Worldwide / Unrestricted,North America
Min_Salary_USD_Annual,37896.0,42772.38,49901.11,50000.0,55000.0
Max_Salary_USD_Annual,63160.0,49901.11,57029.84,75000.0,75000.0
Avg_Salary_USD_Annual,50528.0,46336.745,53465.475,62500.0,65000.0
Language,en,en,en,en,en
Director,0,0,0,0,0
Entry-level,0,0,0,0,1
Executive,0,0,0,0,0
Manager,0,0,1,0,0
Mid-level,1,0,0,1,0
Senior,0,1,0,0,0

In [ ]:
df_no_contractors[(df_no_contractors['Standard Category'] == 'Legal')].sort_values('Min_Salary_USD_Annual' ).head(5).T
#base on data 14661
# Separate full-time and part-time jobs to prevent inaccurate salary comparisons
# Apply normalization based on employment type and working hours before conducting EDA

,23675,14661,10442,9051,25435
Title,Paralegal with a talent for customer service (...,Fractional Chief Legal Officer (CLO),Property Transactions Associate (Remote - PH B...,V105C - California Trust Administration Paralegal,V104 - Legal Client Intake Coordinator (Family...
Company Name,Codekeeper,Learntastic,Cosy Hauz,Job Duck,Job Duck
Company Slug,codekeeper,learntastic,cosy-hauz,job-duck,job-duck
seniority,Mid-level,Executive,Mid-level,Mid-level,Mid-level
Employment Type,Full Time,Part Time,Full Time,Full Time,Full Time
Parent Categories,"Legal, Customer Service",NaN,NaN,Legal,Sales
Category,"Paralegal, Legal-Technology, Customer-Success,...","Fractional-Chief-Legal-Officer, Fractional-CLO...","Property-Transactions, Real-Estate, Legal-Supp...","Paralegal, Trust-Administration-Paralegal, Leg...","Legal-Intake-Specialist, Client-Services-Coord..."
Location Restrictions,Colombia,United States,Philippines,United States,United States
Timezone Restrictions,Any,Any,Any,Any,Any
Min Salary,10000.0,1000.0,800.0,1142.0,1142.0
Max Salary,100000.0,2500.0,900.0,1220.0,1220.0
Salary Period,annual,monthly,monthly,monthly,monthly
Currency,USD,USD,GBP,USD,USD
Published Date,1786173368,1786566616,1786731409,1786757807,1786128463
Published Date(STD),2026-08-08 00:00:00,2026-08-13 00:00:00,2026-08-14 00:00:00,2026-08-15 00:00:00,2026-08-07 00:00:00
Expiry Date,1791357367,1789005399,1791915408,1791941807,1791312462
Expiry Date(STD),2026-10-07 00:00:00,2026-09-10 00:00:00,2026-10-13 00:00:00,2026-10-14 00:00:00,2026-10-06 00:00:00
Application Link,https://himalayas.app/companies/codekeeper/job...,https://himalayas.app/companies/learntastic/jo...,https://himalayas.app/companies/cosy-hauz/jobs...,https://himalayas.app/companies/job-duck/jobs/...,https://himalayas.app/companies/job-duck/jobs/...
Excerpt,Paralegal with a talent for customer service (...,About Learntastic: LearnTastic is a fast-growi...,Role OverviewAs a Property Conveyancing Parale...,"For ambitious, culturally diverse, curious min...","For ambitious, culturally diverse, curious min..."
GUID,https://himalayas.app/companies/codekeeper/job...,https://himalayas.app/companies/learntastic/jo...,https://himalayas.app/companies/cosy-hauz/jobs...,https://himalayas.app/companies/job-duck/jobs/...,https://himalayas.app/companies/job-duck/jobs/...
Standard Category,Legal,Legal,Legal,Legal,Legal
Secondary Category,Customer Service,NaN,NaN,NaN,Customer Service
Region,LATAM,North America,Other Regions,North America,North America
Min_Salary_USD_Annual,10000.0,12000.0,12911.5584,13704.0,13704.0
Max_Salary_USD_Annual,100000.0,30000.0,14525.5032,14640.0,14640.0
Avg_Salary_USD_Annual,55000.0,21000.0,13718.5308,14172.0,14172.0
Language,en,en,en,en,en
Director,0,0,0,0,0
Entry-level,0,0,0,0,0
Executive,0,1,0,0,0
Manager,0,0,0,0,0
Mid-level,1,0,1,1,1
Senior,0,0,0,0,0

In [ ]:
# فیلتر خودکار برای بررسی سریع حقوق‌های بالای ۵۰۰ هزار دلار
high_salary_check = df_no_contractors[df_no_contractors['Avg_Salary_USD_Annual'] > 500000][
    ['Title', 'Standard Category', 'Employment Type', 'Salary Period', 'Avg_Salary_USD_Annual']
]
high_salary_check.head(10)

,Title,Standard Category,Employment Type,Salary Period,Avg_Salary_USD_Annual
334,Cybersecurity Co-Founder / CPTO (100 % remote)...,IT & Cybersecurity,Full Time,annual,576750.0
1153,100% Remote MSK ( with a Mix of Diagnostic Rad...,Healthcare,Full Time,annual,550000.0
1621,Head of Operations,Operations & Management,Full Time,annual,525000.0
4049,"VP, Infrastructure Engineering",Engineering,Full Time,annual,522450.0
5358,Radiologist - BC/BE Flexible Scheduling,Healthcare,Full Time,annual,512500.0
13368,Evening Remote Emergency Radiologist - Northsi...,Healthcare,Full Time,annual,600000.0
13468,Emergency Radiologist Overnight – Remote - Rad...,Healthcare,Full Time,annual,600000.0
17295,Day Musculoskeletal Radiologist – Radiology Pa...,Healthcare,Full Time,annual,550000.0
17663,Early Morning General Radiologist 7 on/7 off,Healthcare,Full Time,annual,512500.0
30923,"Member of Technical Staff, Economics Research",Finance & Accounting,Full Time,annual,600000.0

In [ ]:
# Identify potential salary outliers and normalization errors above $500k.
# High values in hourly/monthly contractor jobs indicate calculation flaws.

# Validate high-salary full-time jobs after excluding contractor roles.
# High salaries above $500k are legitimate executive and medical roles (e.g., Radiologists, VPs).



#important data:
#Data & AI
#min     = 9,984
#max     = 624,000
#mean    = 146,488
#median  = 126,973
# we will show it on EDA

#نباید در EDA بنویسی:

#Finance & Accounting has an average salary of $98,750.

#بدون اینکه اشاره کنی فقط 3 آگهی Salaryدار داری.
#Contractors must be splitted by plotly color or in_memory df in EDA

In [ ]:
#Checkning Other STD categories to enhance the category mappinng:
df[df['Standard Category'] == 'Other'].sort_values('Avg_Salary_USD_Annual', ascending=False)[['Title', 'Parent Categories','Category', 'Excerpt' ]]

,Title,Parent Categories,Category,Excerpt
7112,Fellow - Industry/Domain Expert,NaN,"Business-Domain-Expert, Domain-Expert, Consult...",Disclaimer: Applications for the current cohor...
20237,AUXILIAR ADMINISTRATIVO - TURISMO,NaN,"Auxiliar-Administrativo, Tourism-Administratio...",Estamos em busca de um profissional para refor...
35689,Interest Form,NaN,"Interest-Form, Express-Interest, Expression-Of...","Hey there! Welcome to Practicing the Way's ""G..."
37389,Uppdragschef-Vivant Assistans,NaN,"Uppdragschef, Personalassistent-Rekrytering, A...",Om Vivant AssistansVivant Assistans är ett väx...
40241,Candidature Spontanée,NaN,"Spontaneous-Application, General-Applications,...",Vous ne trouvez pas de poste correspondant exa...
41233,Wedding Planner // Organisateur de mariages In...,NaN,"Wedding-Planning, Event-Planning, Event-Coordi...",Jules & moi organise & décore des mariages dep...
45590,Your Dream Job,NaN,"Dream-Job-Portal, Dream-Job, Career-Developmen...",Want to challenge yourself at a purpose led or...
49115,Candidature Spontanée,NaN,"Open-Applications, Speculative-Application, Se...","Laisse-nous ton CV, ainsi qu’un court texte ré..."

In [ ]:
#How many jobs are in STD categories:
(df.groupby('Standard Category')['Title'].count()).sort_values(ascending=False)

Standard Category
Sales                      6425
Software Development       5142
Healthcare                 5005
Customer Service           3741
Data & AI                  3309
Engineering                3249
Operations & Management    3205
Marketing                  2488
Finance & Accounting       2346
IT & Cybersecurity         1844
Human Resources            1700
Product                    1297
Design & Creative          1061
Writing & Content          1026
Education                   887
Legal                       826
Research & Science          269
Other                         8
Name: Title, dtype: int64

In [ ]:
#Must: Min ≤ Avg ≤ Max

df[
    df['Min_Salary_USD_Annual'].notna() & df['Max_Salary_USD_Annual'].notna() &
    (
        (df['Min_Salary_USD_Annual'] > df['Max_Salary_USD_Annual']) |(df['Avg_Salary_USD_Annual'] < df['Min_Salary_USD_Annual']) |
        (df['Avg_Salary_USD_Annual'] > df['Max_Salary_USD_Annual'])
    )
][[
    'Title', 'Min_Salary_USD_Annual', 'Max_Salary_USD_Annual', 'Avg_Salary_USD_Annual'
]]

Empty DataFrame
Columns: [Title, Min_Salary_USD_Annual, Max_Salary_USD_Annual, Avg_Salary_USD_Annual]
Index: []

In [ ]:
(df['Min_Salary_USD_Annual'] < 0).sum()
(df['Max_Salary_USD_Annual'] < 0).sum()

np.int64(0)

In [338]:
#Final save (Road to EDA)
df = df.reset_index(drop=True)
df.to_csv('../3_data/cleaned.csv')
df

,Title,Company Name,Company Slug,seniority,Employment Type,Parent Categories,Category,Location Restrictions,Timezone Restrictions,Min Salary,...,Min_Salary_USD_Annual,Max_Salary_USD_Annual,Avg_Salary_USD_Annual,Language,Director,Entry-level,Executive,Manager,Mid-level,Senior
0,Senior Security Researcher,CommIT,commit,Senior,Full Time,NaN,"Security-Researcher, Cybersecurity-Researcher,...",Ukraine,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
1,"Director, Revenue Cycle Management",SimpliFed,simplifed,Director,Full Time,NaN,"Revenue-Cycle-Management, Healthcare-Billing, ...",United States,Any,140000.0,...,140000.000,140000.000,140000.00,en,1,0,0,0,0,0
2,SAP IM-MM Consultant 2724,Xideral,xideral,Senior,Full Time,NaN,"SAP-IM-MM-Consultant, Sap-Functional-Consultan...",Mexico,Any,NaN,...,NaN,NaN,NaN,es,0,0,0,0,0,1
3,Creator Talent Manager,Grail Talent,grail-talent,Manager,Full Time,Human Resources,"Talent-Management, Influencer-Marketing, Creat...",Canada,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,1,0,0
4,Senior Program Officer,Pride Foundation,pride-foundation,Senior,Full Time,Product,"Grantmaking, Nonprofit-and-Philanthropy, Commu...",French Polynesia,Any,89000.0,...,89000.000,94000.000,91500.00,en,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43823,Piping VDC Detailer III,Upgrade Resources,upgrade-resources,Senior,Full Time,NaN,"Piping-Detailer, Mechanical-Piping-Detailer, S...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
43824,DFC - Lead ISSO,cFocus Software Incorporated,cfocus-software-incorporated,Senior,Full Time,NaN,"ISSO-Lead, Information-Systems-Security-Office...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
43825,Romanian - English Remote Interpreter,Kalam,kalam,Senior,Contractor,NaN,"Interpreting, Language-Services, Translation-a...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1
43826,"Bilingual Technical Support Specialist, EV Cha...",ChargeLab Inc.,chargelab-inc,Entry-level,Full Time,Customer Service,"Technical-Support, Customer-Support, Bilingual...",Canada,Any,55000.0,...,39208.015,46336.745,42772.38,en,0,1,0,0,0,0
43827,EGL - Legal Admin VA,Scale-X Solutions,scale-x-solutions,Senior,Full Time,Human Resources,"Virtual-Assistant, Legal-Admin, Legal-Assistan...",United States,Any,NaN,...,NaN,NaN,NaN,en,0,0,0,0,0,1